### ISSUE TITLE
feature/Link Checkout button to Checkout page

### ISSUE THREAD

**Issue by jm2601** [Bay-Valley-Tech-Code-Academy/UI-Tool-Kit#64]
Design and implement a basic layout for the checkout page, including text input fields for customer information and payment method. The fields can remain placeholders for now, to be filled in later.

**Comment by davidxiong117** [comment]
just a quick note, i added a button that links the checkout page to the cart page, but the checkout page itself is not present. since kimberly is assigned, she can take care of the checkout page. i'm here to help as well.
